export const DEFAULT_ACTION = "DEFAULT_ACTION";

export const SET_USER = "SET_USER";
export const SET_LOCATION = "SET_LOCATION";
export const UNSET_USER = "UNSET_USER";
export const LOGIN_LOADING = "LOGIN_LOADING";

export const SET_SPS = "SET_SPS";
export const SPS_LOADING = "SPS_LOADING";
export const ERROR_SPS = "ERROR_SPS";

export const SET_SERVICES = "SET_SERVICES";
export const SERVICES_LOADING = "SERVICES_LOADING";
export const ERROR_SERVICES = "ERROR_SERVICES";

export const GET_PRODUCTS = "GET_PRODUCTS";
export const GET_CATEGORIES = "GET_CATEGORIES";
export const STORE_LOADING = "STORE_LOADING";
export const ERROR_STORE = "ERROR_STORE";

// export const ADD_PRODUCT = "ADD_PRODUCT";
// export const SET_QUANTITY = "SET_QUANTITY";
// export const REMOVE_PRODUCT = "REMOVE_PRODUCT"

export const GET_COMMANDS = "GET_COMMANDS"
export const ERROR_GET_COMMANDS = "ERROR_GET_COMMANDS"
export const GET_COMMANDS_LOADING = "GET_COMMANDS_LOADING";

export const GET_INTERVENTIONS = "GET_INTERVENTIONS"
export const ERROR_GET_INTERVENTIONS = "ERROR_GET_INTERVENTIONS"
export const GET_INTERVENTIONS_LOADING = "GET_INTERVENTIONS_LOADING";

export const SET_COMMAND = "SET_COMMAND";
export const CANCEL_COMMAND = "CANCEL_COMMAND";
export const ADD_PRODUCT = "ADD_PRODUCT";
export const ERROR_CART = "ERROR_CART"
export const CART_LOADING = "CART_LOADING"
export const REMOVE_PRODUCT = "REMOVE_PRODUCT";
export const ADD_QUANTITY = "ADD_QUANTITY";
export const REMOVE_QUANTITY = "REMOVE_QUANTITY";



