export const LOADING_ARTICLES = "LOADING_ARTICLES";
export const SET_ARTICLES = "SET_ARTICLES";
export const ERROR_ARTICLES = "ERROR_ARTICLES";

export const LOADING_RESULTS = "LOADING_RESULTS";
export const SET_RESULTS = "SET_RESULTS";
export const ERROR_SEARCH = "ERROR_SEARCH";

export const LOADING_TOPICS = "LOADING_TOPICS";
export const SET_TOPICS = "SET_TOPICS";

export const LOADING_CATEGORIES = "LOADING_CATEGORIES";
export const SET_CATEGORIES = "SET_CATEGORIES";
export const ERROR_CATEGORIES = "ERROR_CATEGORIES";

export const LOADING_SOURCES = "LOADING_SOURCES";
export const SET_SOURCES = "SET_SOURCES";
export const ERROR_SOURCES = "ERROR_SOURCES";

export const SET_PREFERENCE = "SET_PREFERENCE";

export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";

export const SET_TOLOAD = "SET_TOLOAD";
