export const LOADING_ARTICLES = "LOADING_ARTICLES";
export const SET_ARTICLES = "SET_ARTICLES";
export const ERROR_ARTICLES = "ERROR_ARTICLES";

export const LOADING_RESULTS = "LOADING_RESULTS";
export const SET_RESULTS = "SET_RESULTS";
export const ERROR_SEARCH = "ERROR_SEARCH";

export const LOADING_TOPICS = "LOADING_TOPICS";
export const SET_TOPICS = "SET_TOPICS";

export const LOADING_CATEGORIES = "LOADING_CATEGORIES";
export const SET_CATEGORIES = "SET_CATEGORIES";

export const ADD_BOOKMARK = "ADD_BOOKMARK";
export const REMOVE_BOOKMARK = "REMOVE_BOOKMARK";
